from pymc_experimental.distributions import histogram_utils
from pymc_experimental.distributions.histogram_utils import histogram_approximation
from pymc_experimental.distributions.continuous import (
	GeneralizedGamma,
)