name: release-pipeline

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install release tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build distribution package
        run: python setup.py sdist bdist_wheel
      - name: Check version number match
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          # The GITHUB_REF should be something like "refs/tags/v1.2.3"
          # Make sure the package version is the same as the tag
          grep -Rq "^Version: ${GITHUB_REF:11}$" pymc.egg-info/PKG-INFO
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_PYMC }}
        run: |
          twine check dist/*
          twine upload --repository pypi --username __token__ --password ${PYPI_TOKEN} dist/*
  test-install-job:
    needs: release-job
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Give PyPI a chance to update the index
      run: sleep 240
    - name: Install from PyPI
      run: |
        pip install pymc-experimental==${GITHUB_REF:11}
